version: "3"
services:
  portfolio-performance:
    image: quallenbezwinger/portfolio-performance:0.6
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - /home/dkoehler/dev/docker-volumes/pp/config:/config
      - /home/dkoehler/dev/docker-volumes/pp/workspace:/opt/portfolio/workspace
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      TZ: "Europe/Berlin" 
