version: "3"
services:
  portfolio-performance:
    image: cubinet/portfolio-performance:latest
    container_name: portfolio-performance
    # restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ../mounts/config:/config
      - ../mounts/workspace:/opt/portfolio/workspace
    environment:
      USER_ID: 501
      GROUP_ID: 20
      DISPLAY_WIDTH: 3200
      DISPLAY_HEIGHT: 1350
      TZ: "Europe/Berlin" 
