version: "3"
services:
  portfolio-performance:
    image: quallenbezwinger/portfolio-performance:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - /mnt/portfolio:/opt/portfolio/workspace
    environment:
      USER_ID: 0
      GROUP_ID: 0
      TZ: "Europe/Berlin" 
